{{ if .Values.global.externalSecrets.deploy }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: manifestservice-g3auto
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{include "cluster-secret-store" .}}
    kind: ClusterSecretStore
  target:
    name: manifestservice-g3auto
    creationPolicy: Owner
  dataFrom:
  - extract:
      #name of secret in secrets manager
      key: {{include "manifestservice-g3auto" .}}
{{- end }}