# TODO: evaluate if we need this
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rbac.rbacServiceName }}
  labels:
    service: {{ .Values.rbac.rbacServiceName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.rbac.rbacServiceName }}
      port: {{ .Values.rbac.servicePort }}
      targetPort: {{ .Values.rbac.servicePort }}
      nodePort: null
  selector:
    {{- include "ambassador.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador
  name: ambassador-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: proxy
  selector:
    service: ambassador