remote: origin
target-branch: master
chart-dirs:
  - helm
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - elastic=https://helm.elastic.co
helm-extra-args: --timeout 600s
check-version-increment: true
debug: true
validate-maintainers: false
helm-dependency-extra-args: "--skip-refresh"