apiVersion: apps/v1
kind: Deployment
metadata:
  name: pidgin-deployment
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pidgin.selectorLabels" . | nindent 6 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        # gen3 networkpolicy labels
        netnolimit: 'yes'
        public: 'yes'
      {{- if eq (include "pidgin.ddEnabled" . ) "true" }}
        tags.datadoghq.com/service: "pidgin"
        # TODO: move this to helpers so we can have this populated from a configmap
        tags.datadoghq.com/env: {{ .Values.dataDog.env }}
        tags.datadoghq.com/version: {{ .Values.image.tag | default .Chart.AppVersion }}
      {{- end }}
        {{- include "pidgin.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env: 
            - name: GEN3_DEBUG
              value: "False"
          livenessProbe:
            httpGet:
              path: /_status
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /_status
              port: 80
          ports:
            - containerPort: 80
            - containerPort: 443
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}