# Default values for dicom-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Deployment

# -- (map) Configuration for autoscaling the number of replicas
autoscaling:
  # -- (bool) Whether autoscaling is enabled
  enabled: false
  # -- (int) The minimum number of replicas to scale down to
  minReplicas: 1
  # -- (int) The maximum number of replicas to scale up to
  maxReplicas: 100
  # -- (int) The target CPU utilization percentage for autoscaling
  targetCPUUtilizationPercentage: 80

# -- (int) Number of replicas for the deployment.
replicaCount: 1

# -- (list) Volumes to attach to the pod.
volumes:
  - name: config-volume-g3auto
    secret:
      secretName: orthanc-g3auto

# -- (map) Docker image information.
image:
  # -- (string) Docker repository.
  repository: quay.io/cdis/gen3-orthanc
  # -- (string) Docker pull policy.
  pullPolicy: Always
  # -- (string) Overrides the image tag whose default is the chart appVersion.
  tag: "master"

# -- (list) Volumes to mount to the pod.
volumeMounts:
  - name: config-volume-g3auto
    readOnly: true
    mountPath: /etc/orthanc/orthanc_config_overwrites.json
    subPath: orthanc_config_overwrites.json

# Service and Pod
# -- (map) Kubernetes service information.
service:
  # -- (int) The port number that the service exposes.
  port: 80
  # -- (int) The port on the host machine that traffic is directed to.
  targetport: 8042

# -- (map) Secret information
secrets:
  # -- (bool) Whether or not the password protection is enabled.
  authenticationEnabled: false
  # -- (bool) Whether to enable index. If set to "false", Orthanc will continue to use its default SQLite back-end.
  enableIndex: true
  # -- (bool) Whether to enable storage. If set to "false", Orthanc will continue to use its default filesystem storage area.
  enableStorage: true
  # -- (string) Port for Postgres.
  port: "5432"
  # -- (string) Hostname for postgres server.
  host: postgres-postgresql.postgres.svc.cluster.local
  # -- (string) Database name for postgres.
  dataBase: postgres
  # -- (string) Username for postgres.
  userName: postgres
  # -- (string) Password for Postgres.
  password: postgres
  # -- (int) The number of connections from the index plugin to the PostgreSQL database.
  indexConnectionsCount: 5
  # -- (bool) Whether to lock the database.
  lock: false
