kind: Pod 
apiVersion: v1 
metadata:
  name: etl

spec:
  # Add the ConfigMap as a volume to the Pod
  volumes:
    # `name` here must match the name
    # specified in the volume mount
    - name: creds-configmap-volume
      # Populate the volume with config map data
      configMap:
        # `name` here must match the name 
        # specified in the ConfigMap's YAML 
        name: credentials
    - name: sheepdog-creds
      secret:
        secretName: sheepdog-dbcreds
    - name: fence-creds
      secret:
        secretName: fence-dbcreds
    - name: useryaml
      # Populate the volume with config map data
      configMap:
        # `name` here must match the name 
        # specified in the ConfigMap's YAML 
        name: useryaml

  containers:
    - name: container-configmap
      image: python:3.9.16-slim-buster
      # Mount the volume that contains the configuration data 
      # into your container filesystem
      volumeMounts:
        # `name` here must match the name
        # from the volumes section of this pod

        # Gen3 creds file
        - name: creds-configmap-volume
          mountPath: /creds/credentials.json
          subPath: credentials.json

        # Fence config
        - name: fence-creds
          mountPath: /creds/fence-creds

        # Sheepdog creds
        - name: sheepdog-creds
          mountPath: /creds/sheepdog-creds

        # User yaml
        - name: useryaml
          mountPath: /creds/user.yaml
          subPath: useryaml

      command: ["/bin/bash" ]
      args:
        - "-c"
        - |
          echo $REVPROXY_SERVICE_SERVICE_HOST aced-training.compbio.ohsu.edu >> /etc/hosts
          apt-get -y update; apt-get -y install curl iputils-ping gcc
          curl https://aced-public.s3.us-west-2.amazonaws.com/aced.json > aced.json;
          pip install gen3
          while true; do sleep 30; done;
      