kind: Pod 
apiVersion: v1 
metadata:
  name: etl

spec:
  volumes:
    # To create the crredentials config run --
    # kubectl create configmap credentials --from-file credentials-templates
    - name: creds-configmap-volume
      configMap:
        name: credentials

    - name: sheepdog-creds
      secret:
        secretName: sheepdog-dbcreds

    - name: useryaml
      configMap:
        name: useryaml

    - name: host-mount
      hostPath:
        path: /Users/walsbr/aced/data_model/studies        

  containers:
    - name: container-configmap
      image: python:3.9.16-slim-buster
      volumeMounts:
        # Gen3 credentials file
        - name: creds-configmap-volume
          mountPath: /creds/credentials.json
          subPath: credentials.json

        # Sheepdog creds, secrets defined in helm/sheepdog/templates/deployment.yaml
        - name: sheepdog-creds
          mountPath: /creds/sheepdog-creds

        # User yaml, configmap defined in helm/fence/templates/useryaml-job.yaml
        - name: useryaml
          mountPath: /creds/user.yaml
          subPath: useryaml

        # studies
        - name: host-mount
          mountPath: /studies

      command: ["/bin/bash" ]
      args:
        - "-c"
        - |
          # Add the revproxy-service IP address to the pod's hosts file
          echo $REVPROXY_SERVICE_SERVICE_HOST aced-training.compbio.ohsu.edu >> /etc/hosts
          
          # Fetch the schema
          curl https://aced-public.s3.us-west-2.amazonaws.com/aced.json > aced.json;

          # Install network and development tools. gcc is necessary for installing the gen3 SDK.
          apt-get -y update; apt-get -y install curl iputils-ping gcc

          # move the credentials file to a well known spot
          # https://github.com/uc-cdis/gen3sdk-python/blob/master/docs/reference/sdkClasses.md#gen3auth
          mkdir ~/.gen3
          cp /creds/credentials.json ~/.gen3/credentials.json

          # Install dependencies
          apt install git libpq-dev python3-dev build-essential vim unzip  -y

          # Until we fix in helm env, setup well known postgres env variables
          cat  << EOF >> ~/.bashrc
          export PGDB=`cat /creds/sheepdog-creds/database`
          export PGPASSWORD=`cat /creds/sheepdog-creds/password`
          export PGUSER=`cat /creds/sheepdog-creds/username`
          export PGHOST=`cat /creds/sheepdog-creds/host`
          export DBREADY=`cat /creds/sheepdog-creds/dbcreated`
          export PGPORT=`cat /creds/sheepdog-creds/port`
          EOF

          git clone https://github.com/ACED-IDP/data_model
          cd data_model
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          # mac silicon, build from scratch, avoids Postgresql SCRAM authentication problem
          pip install  psycopg2

          # For development purposes, extends the lifespan of the pod to let us exec into it.
          while true; do sleep 30; done;
      
