kind: Pod 
apiVersion: v1 
metadata:
  name: etl

spec:
  volumes:
    # To create the crredentials config run --
    # kubectl create configmap credentials --from-file credentials-templates
    - name: creds-configmap-volume
      configMap:
        name: credentials

    - name: sheepdog-creds
      secret:
        secretName: sheepdog-dbcreds

    - name: useryaml
      configMap:
        name: useryaml

  containers:
    - name: container-configmap
      image: python:3.9.16-slim-buster
      volumeMounts:
        # Gen3 credentials file
        - name: creds-configmap-volume
          mountPath: /creds/credentials.json
          subPath: credentials.json

        # Sheepdog creds, secrets defined in helm/sheepdog/templates/deployment.yaml
        - name: sheepdog-creds
          mountPath: /creds/sheepdog-creds

        # User yaml, configmap defined in helm/fence/templates/useryaml-job.yaml
        - name: useryaml
          mountPath: /creds/user.yaml
          subPath: useryaml

      command: ["/bin/bash" ]
      args:
        - "-c"
        - |
          # Add the revproxy-service IP address to the pod's hosts file
          echo $REVPROXY_SERVICE_SERVICE_HOST aced-training.compbio.ohsu.edu >> /etc/hosts
          
          # Fetch the schema
          curl https://aced-public.s3.us-west-2.amazonaws.com/aced.json > aced.json;

          # Install network and development tools. gcc is necessary for installing the gen3 SDK.
          apt-get -y update; apt-get -y install curl iputils-ping gcc
          pip install gen3

          # For development purposes, extends the lifespan of the pod to let us exec into it.
          while true; do sleep 30; done;
      
