apiVersion: apps/v1
kind: Deployment
metadata:
  name: guppy-deployment
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "guppy.selectorLabels" . | nindent 6 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        # gen3 networkpolicy labels
        netnolimit: 'yes'
        public: 'yes'
      {{- if eq (include "guppy.ddEnabled" . ) "true" }}
        tags.datadoghq.com/service: "guppy"
        # TODO: move this to helpers so we can have this populated from a configmap
        tags.datadoghq.com/env: {{ .Values.dataDog.env }}
        tags.datadoghq.com/version: {{ .Values.image.tag | default .Chart.AppVersion }}
      {{- end }}
        {{- include "guppy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      {{- with .Values.volumes}}
      volumes: 
        {{- toYaml . | nindent 8}}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          livenessProbe:
            httpGet:
              path: /_status
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 30
          readinessProbe:
          readinessProbe:
            httpGet:
              path: /_status
              port: 8000
          ports:
            - containerPort: 8000
          env: 
            - name: GUPPY_PORT
              value: "8000"
            - name: GUPPY_CONFIG_FILEPATH
              value: /guppy/guppy_config.json
            - name: GEN3_ES_ENDPOINT
              value: {{ default "elasticsearch:9200"  .Values.esEndpoint }}
            {{- with .Values.arboristUrl }}
            - name: GEN3_ARBORIST_ENDPOINT
              value: {{ . }}
            {{- end }}
            - name: TIER_ACCESS_LEVEL
              value: {{ include "guppy.tierAccessLevel" . }}
            {{- with .Values.tierAccessLimit }}
            - name: TIER_ACCESS_LIMIT
              value: {{ . | quote }}
            {{- end }}


          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}