{{ include "common.externalSecret.db" . }}
---
{{ if .Values.global.externalSecrets.deploy }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: indexd-service-creds
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{include "cluster-secret-store" .}}
    kind: ClusterSecretStore
  target:
    name: indexd-service-creds
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.externalSecrets.serviceCreds }}
      conversionStrategy: Default
      decodingStrategy: None
{{- end }}