apiVersion: v1
kind: Secret
metadata:
  name: indexd-secret
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
{{ (.Files.Glob "indexd-secret/*").AsSecrets | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: indexd-creds
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-10"
type: Opaque
stringData:
  creds.json: |-
    {
      "db_host": {{ .Values.database.host | quote }},
      "db_username": {{ .Values.database.user | quote}},
      "db_password": {{ include "indexd.postgres.password" . | quote }},
      "db_database": {{ .Values.database.dbname | quote }},
      "user_db": {
        "fence": {{ include "indexd-fence-creds" . | quote }},
        "gdcapi": {{ include "indexd-sheepdog-creds" . | quote }},
        "gateway": {{ include "indexd-gateway-creds" . | quote }}
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: indexd-service-creds
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-10"
type: Opaque
stringData:
  fence: {{ include "indexd-fence-creds" . | quote }}
  gdcapi: {{ include "indexd-sheepdog-creds" . | quote }}
  gateway: {{ include "indexd-gateway-creds" . | quote }}