apiVersion: v1
kind: Secret
metadata:
  name: indexd-secret
type: Opaque
data:
{{ (.Files.Glob "indexd-secret/*").AsSecrets | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: indexd-creds
type: Opaque
stringData:
  creds.json: |-
    {
      "db_host": {{ default "indexd-postgresql" .Values.secrets.db.host | quote }},
      "db_username": {{ default "postgres" .Values.secrets.db.username | quote }},
      "db_password": {{ default .Values.global.postgresql.auth.postgresPassword .Values.secrets.db.password | quote }},
      "db_database": {{ default .Values.global.postgresql.auth.database .Values.secrets.db.database | quote }},
      "user_db": {
        "fence": {{ default (randAlphaNum 32) .Values.secrets.userdb.fence | quote }},
        "gdcapi": {{ default (randAlphaNum 32) .Values.secrets.userdb.gdcapi | quote }},
        "gateway": {{ default (randAlphaNum 32) .Values.secrets.userdb.gateway | quote }}
      }
    }