apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit
  labels:
    helm.sh/chart: audit-0.1.0
    app.kubernetes.io/name: audit
    app.kubernetes.io/instance: audit
    app.kubernetes.io/version: "2021.12"
    app.kubernetes.io/managed-by: Helm
    release: production
    dbaudit: "yes"
    public: "yes"
    netnolimit: "yes"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: audit
      app.kubernetes.io/instance: audit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: audit
        app.kubernetes.io/instance: audit
    spec:
      serviceAccountName: audit-sa
      securityContext:
        {}
      volumes:
        - name: config-volume
          secret:
            secretName: "audit-g3auto"
      containers:
        - name: audit
          securityContext:
            fsGroup: 101
          image: "quay.io/cdis/audit:2021.12"
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          livenessProbe:
            httpGet:
              path: /_status
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /_status
              port: 80
          resources:
            limits:
              cpu: 0.8
              memory: 1024Mi
            requests:
              cpu: 0.4
              memory: 512Mi
          env:
            - name: DEBUG
              value: "false"
                  optional: true
            - name: ARBORIST_URL
              valueFrom:
                configMapKeyRef:
                  name: manifest-global
                  key: arborist_url
                  optional: true
        volumeMounts:
          - mountPath: /src/audit-service-config.yaml
            name: config-volume
            readOnly: true
            subPath: audit-service-config.yaml
      initContainers:
        - name: audit-db-migrate
          image: "quay.io/cdis/audit:2021.12"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
            - name: container
              containerPort: 6567
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /_status
              port: http
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /_status
              port: http
          resources:
            limits:
              cpu: 0.8
              memory: 1024Mi
            requests:
              cpu: 0.4
              memory: 512Mi
          command: ["/bin/bash"]
          args:
            - "-c"
            - |
              /env/bin/alembic upgrade head
        volumeMounts:
          - mountPath: /src/audit-service-config.yaml
            name: config-volume
            readOnly: true
            subPath: audit-service-config.yaml
      affinity:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - audit
          topologyKey: kubernetes.io/hostname

