apiVersion: v1
kind: Secret
metadata:
  name: peregrine-secret
type: Opaque
data:
{{ (.Files.Glob "peregrine-secret/*").AsSecrets | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: peregrine-creds
type: Opaque
stringData:
  creds.json: |-
    {
      "fence_host": {{ default "fence-postgresql" .Values.secrets.fence.db.host | quote }},
      "fence_username": {{ default "postgres" .Values.secrets.fence.db.username | quote }},
      "fence_password": {{ default .Values.global.postgresql.auth.postgresPassword .Values.secrets.fence.db.password | quote }},
      "fence_database": {{ default .Values.global.postgresql.auth.database .Values.secrets.fence.db.database | quote }},
      "db_host": {{ .Values.database.host | quote }},
      "db_username": {{ .Values.database.user | quote}},
      "db_password": {{ include "peregrine.postgres.password" . | quote }},
      "db_database": {{ .Values.database.dbname | quote }},
      "gdcapi_secret_key": {{ default (randAlphaNum 50) .Values.secrets.gdcapi_secret_key | quote }},
      "hostname": {{ default "ingress.local" .Values.hostname  | quote}}
    }
