---
# Source: guppy/templates/guppy_config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: manifest-guppy
data:
  guppy_config.json: |
      {
        "indices":{"valueFrom":{"configMapKeyRef":{"key":".guppy.indices","name":"manifest-global","optional":false}}}
        ,
        "config_index": "map[valueFrom:map[configMapKeyRef:map[key:.guppy.config_index name:manifest-global optional:false]]]",
        "auth_filter_field": "map[valueFrom:map[configMapKeyRef:map[key:.guppy.auth_filter_field name:manifest-global optional:false]]]",
        "enable_encrypt_whitelist": map[valueFrom:map[configMapKeyRef:map[key:.guppy.enable_encrypt_whitelist name:manifest-global optional:true]]],
        "encrypt_whitelist":{"valueFrom":{"configMapKeyRef":{"key":".guppy.encrypt_whitelist","name":"manifest-global","optional":true}}}
        
      }
---
# Source: guppy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "guppy-service"
  labels:
    helm.sh/chart: guppy-0.1.0
    app.kubernetes.io/name: guppy
    app.kubernetes.io/instance: guppy
    app: guppy
    app.kubernetes.io/version: "2022.08"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: guppy
    app.kubernetes.io/instance: guppy
    app: guppy
  ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: 8000
  type: ClusterIP
---
# Source: guppy/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guppy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: guppy
      app.kubernetes.io/instance: guppy
      app: guppy
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        netnolimit: "yes"
        public: "yes"
        tags.datadoghq.com/service: guppy
        tags.datadoghq.com/version: "2022.08"
        app.kubernetes.io/name: guppy
        app.kubernetes.io/instance: guppy
        app: guppy
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - guppy
              topologyKey: kubernetes.io/hostname
            weight: 100
      automountServiceAccountToken: false
      volumes:
        - configMap:
            items:
            - key: guppy_config.json
              path: guppy_config.json
            name: manifest-guppy
          name: guppy-config
      containers:
        - name: guppy
          image: "quay.io/cdis/guppy:2022.08"
          livenessProbe:
            httpGet:
              path: /_status
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /_status
              port: 8000
          ports:
          - containerPort: 8000
          env:
          - name: GUPPY_PORT
            value: "8000"
          - name: GUPPY_CONFIG_FILEPATH
            value: /guppy/guppy_config.json
          - name: GEN3_ES_ENDPOINT
            value: esproxy-service:9200
          - name: GEN3_ARBORIST_ENDPOINT
            valueFrom:
              configMapKeyRef:
                key: arborist_url
                name: manifest-global
                optional: true
          - name: TIER_ACCESS_LEVEL
            valueFrom:
              configMapKeyRef:
                key: tier_access_level
                name: manifest-global
                optional: true
          - name: TIER_ACCESS_LIMIT
            valueFrom:
              configMapKeyRef:
                key: tier_access_limit
                name: manifest-global
                optional: true
          - name: DD_TRACE_ENABLED
            valueFrom:
              configMapKeyRef:
                key: dd_enabled
                name: manifest-global
                optional: true
          - name: DD_ENV
            valueFrom:
              configMapKeyRef:
                key: environment
                name: manifest-global
                optional: true
          - name: DD_SERVICE
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/service']
          - name: DD_VERSION
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/version']
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_PROFILING_ENABLED
            value: "true"
          - name: DD_TRACE_SAMPLE_RATE
            value: "1"
          - name: DD_TRACE_AGENT_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          volumeMounts:
          - mountPath: /guppy/guppy_config.json
            name: guppy-config
            readOnly: true
            subPath: guppy_config.json
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1
              memory: 2400Mi
            requests:
              cpu: 0.5
              memory: 1024Mi
---
# Source: guppy/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "guppy-test-connection"
  labels:
    helm.sh/chart: guppy-0.1.0
    app.kubernetes.io/name: guppy
    app.kubernetes.io/instance: guppy
    app: guppy
    app.kubernetes.io/version: "2022.08"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['guppy:[map[name:http port:80 protocol:TCP targetPort:8000]]']
  restartPolicy: Never
