apiVersion: v1
kind: Secret
metadata:
  name: {{ include "audit.secretName" . }}
  labels:
    {{- include "audit.labels" . | nindent 4 }}
stringData: 
  audit-service-config.yaml: |-
      ####################
      # SERVER           #
      ####################
      # whether to enable debug logs
      DEBUG: {{ .Values.server.debug }}
      PULL_FROM_QUEUE: {{ .Values.server.pull_from_queue }}
      QUEUE_CONFIG:
      type: aws_sqs
      aws_sqs_config:
          sqs_url: {{ .Values.secrets.sqs.url }}
          region: {{ .Values.secrets.sqs.region }}
      ####################
      # DATABASE         #
      ####################
      DB_HOST: {{ default "audit-postgresql" .Values.secrets.db.host }}
      DB_USER: {{ default "postgres" .Values.secrets.db.user }}
      DB_PASSWORD:  {{ default  .Values.secrets.db.password .Values.global.postgresql.auth.postgresPassword  }}
      DB_DATABASE: {{ default .Values.secrets.db.database .Values.global.postgresql.auth.database	 }}
