{{- range $secretName, $secret := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
{{- range $key, $value := $secret }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
---
{{- end }}