# -- (map) Annotations to add to the pod
podAnnotations:

# -- (map) Configuration for autoscaling the number of replicas
autoscaling:
  # -- (bool) Whether autoscaling is enabled or not
  enabled: false
  # -- (int) The minimum number of replicas to scale down to
  minReplicas: 1
  # -- (int) The maximum number of replicas to scale up to
  maxReplicas: 100
  # -- (int) The target CPU utilization percentage for autoscaling
  targetCPUUtilizationPercentage: 80

# -- (int) Number of replicas for the deployment.
replicaCount: 1

# -- (int) Number of old revisions to retain
revisionHistoryLimit: 2

# -- (map) Rolling update deployment strategy
strategy:
  type: RollingUpdate
  rollingUpdate:
    # -- (int) Number of additional replicas to add during rollout.
    maxSurge: 1
    # -- (int) Maximum amount of pods that can be unavailable during the update.
    maxUnavailable: 0

# -- (bool) Automount the default service account token
automountServiceAccountToken: false

# -- (list) Volumes to attach to the pod
volumes:
  - name: credentials
    secret:
      secretName: aws-es-proxy

# -- (map) Docker image information.
image:
  # -- (string) Docker repository.
  repository: quay.io/cdis/aws-es-proxy
  # -- (string) Docker pull policy.
  pullPolicy: Always
  # -- (string) Overrides the image tag whose default is the chart appVersion.
  tag: ""

# -- (list) List of container ports
ports:
  - containerPort: 9200

# -- (str) Elasticsearch endpoint in AWS
esEndpoint: test.us-east-1.es.amazonaws.com

# -- (list) Volumes to mount to the pod.
volumeMounts:
  - name: credentials
    readOnly: true
    mountPath: /root/.aws

# -- (map) Resource requests and limits for the containers in the pod
resources:
  # -- (map) The amount of resources that the container requests
  requests:
    # -- (string) The amount of CPU requested
    cpu: 0.1
    # -- (string) The amount of memory requested
    memory: 250Mi
  # -- (map) The maximum amount of resources that the container is allowed to use
  limits:
    # -- (string) The maximum amount of memory the container can use
    memory: 2Gi

# -- (map) Kubernetes service information.
service:
  # -- (string) Type of service. Valid values are "ClusterIP", "NodePort", "LoadBalancer", "ExternalName".
  type: ClusterIP
  # -- (int) The port number that the service exposes.
  port: 9200

# -- (map) Secret information
secrets:
  # -- (str) AWS access key ID
  awsAccessKeyId: ""
  # -- (str) AWS secret access key
  awsSecretAccessKey: ""
