# Default values for ambassador.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- (int) Number of replicas for the deployment.
replicaCount: 1

# -- (map) Docker image information.
image:
  # -- (string) Docker repository.
  repository: quay.io/datawire/ambassador
  # -- (string) Docker pull policy.
  pullPolicy: Always
  # -- (string) Overrides the image tag whose default is the chart appVersion.
  tag: "1.4.2"

# -- (list) Docker image pull secrets.
imagePullSecrets: []

# -- (string) Override the name of the chart.
nameOverride: ""

# -- (string) Override the full name of the deployment.
fullnameOverride: ambassador-deployment

# -- (map) Service account to use or create.
serviceAccount:
  # -- (bool) Specifies whether a service account should be created.
  create: true
  # -- (map) Annotations to add to the service account.
  annotations: {}
  # -- (string) The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: ""

# -- (map) Annotations to add to the pod.
podAnnotations:

# -- (map) Labels to add to the pod.
podLabels:

# -- (map) Pod-level security context.
podSecurityContext:
  runAsUser: 8888
  # fsGroup: 2000

# -- (map) Container-level security context.
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# -- (map) Kubernetes service information.
service:
  # -- (string) Type of service. Valid values are "ClusterIP", "NodePort", "LoadBalancer", "ExternalName".
  type: ClusterIP
  # -- (int) The port number that the service exposes.
  port: 8877

# -- (map) Labels to use for selecting the deployment.
selectorLabels:
  service: ambassador

# -- (string) Namespace to use for user resources.
userNamespace: "jupyter-pods"

# -- (map) Resource requests and limits for the containers in the pod
resources:
  # -- (map) The maximum amount of resources that the container is allowed to use
  limits:
    # -- (string) The maximum amount of memory the container can use
    memory: 400Mi
  # -- (map) The amount of resources that the container requests
  requests:
    # -- (string) The amount of CPU requested
    cpu: 100m
    # -- (string) The amount of memory requested
    memory: 100Mi

# -- (map) Configuration for autoscaling the number of replicas
autoscaling:
  # -- (bool) Whether autoscaling is enabled or not
  enabled: false
  # -- (int) The minimum number of replicas to scale down to
  minReplicas: 1
  # -- (int) The maximum number of replicas to scale up to
  maxReplicas: 10
  # -- (int) The target CPU utilization percentage for autoscaling
  targetCPUUtilizationPercentage: 60
  # -- (int) The target memory utilization percentage for autoscaling
  # targetMemoryUtilizationPercentage: 80

# -- (map) Node selector labels.
nodeSelector: {}

# -- (list) Tolerations to use for the deployment.
tolerations: []

# -- (map) Affinity to use for the deployment.
affinity: {}
