{{ if .Values.global.externalSecrets.deploy }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fence-jwt-keys
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{include "cluster-secret-store" .}}
    kind: ClusterSecretStore
  target:
    name: fence-jwt-keys
    creationPolicy: Owner
  dataFrom:
  - extract:
      #name of secret in secrets manager
      key: {{include "fence-jwt-keys" .}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fence-google-app-creds-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{include "cluster-secret-store" .}}
    kind: ClusterSecretStore
  target:
    name: fence-google-app-creds-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      #name of secret in secrets manager
      key: {{include "fence-google-app-creds-secret" .}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fence-google-storage-creds-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{include "cluster-secret-store" .}}
    kind: ClusterSecretStore
  target:
    name: fence-google-storage-creds-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      #name of secret in secrets manager
      key: {{include "fence-google-storage-creds-secret" .}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fence-config
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{include "cluster-secret-store" .}}
    kind: ClusterSecretStore
  target:
    name: fence-config
    creationPolicy: Owner
  dataFrom:
  - extract:
      #name of secret in secrets manager
      key: {{include "fence-config" .}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $.Chart.Name }}-dbcreds
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{include "cluster-secret-store" .}}
    kind: ClusterSecretStore
  target:
    name: {{ $.Chart.Name }}-dbcreds
    creationPolicy: Owner
  dataFrom:
  - extract:
      #name of secret in secrets manager
      key: {{include "fence-sm-dbcreds" .}}
{{- end }}