apiVersion: v1
kind: Secret
metadata:
  name: fence-config
stringData:
  fence-config.yaml: |
    BASE_URL: '{{ .Values.FENCE_CONFIG.BASE_URL }}'
    DB: 'postgresql://{{ .Values.database.user }}:{{ include  "fence.postgres.password" . }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.dbname }}'
    {{- with .Values.FENCE_CONFIG }}
    {{- toYaml . | nindent 4 }}
    {{ end }}
  