apiVersion: batch/v1
kind: Job
metadata:
  name: grip-initdb
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        app: gen3job
    spec:
      containers:
      - name: grip
        # Use an Alpine image with curl pre-installed
        image: "curlimages/curl:latest"
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args:
          - "-c"
          - |
            echo "Waiting for the grip service to be available..."
            until curl -s --head --request GET http://{{ .Values.serviceName }}:8201/graphql/_status | grep "200 OK" > /dev/null; do
              echo "Grip service not ready, retrying in 5 seconds..."
              sleep 5
            done
            echo "Grip is online. Creating CALIPER Graph"
            curl -X POST 'http://{{ .Values.serviceName }}:8201/v1/graph/CALIPER'
      restartPolicy: OnFailure
