apiVersion: batch/v1
kind: Job
metadata:
  name: grip-mongo-initdb
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        app: gen3job
    spec:
      containers:
      - name: grip
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
        env:
          {{- toYaml .Values.env | nindent 10 }}
        command: ["/bin/sh" ]
        args:
          - "-c"
          - |
            apk add --no-cache curl && \
            curl -X POST http://local-grip:8201/v1/graph/CALIPER
      restartPolicy: OnFailure
