{{ include "common.db-secret" . }}
---
{{ include "common.db_setup_sa" . }}
---
{{- if .Values.db_restore }}
{{ include "common.s3_pg_restore" . }}
{{- else }}
{{ include "common.db_setup_job" . }}
{{- end -}}