apiVersion: v1
kind: Secret
metadata:
  name: metadata-g3auto
stringData:
  {{- $randomPass := printf "%s%s" "gateway:" (randAlphaNum 32)  }}
  base64Authz.txt: {{  $randomPass | b64enc | quote  }}
  dbcreds.json: |
    {
      "db_host": {{ .Values.database.host | quote }},
      "db_username": {{ .Values.database.user | quote}},
      "db_password": {{ include "metadata.postgres.password" . | quote }},
      "db_database": {{ .Values.database.dbname | quote }}
    }
  metadata.env: | 
    DEBUG={{ .Values.debug}}
    DB_HOST={{ .Values.database.host  }}
    DB_USER={{ .Values.database.user }}
    DB_PASSWORD={{ include "metadata.postgres.password" .  }}
    DB_DATABASE={{ .Values.database.dbname  }}
    ADMIN_LOGINS={{ $randomPass  }}