{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "presigned-url-fence.serviceAccountName" . }}
  labels:
    {{- include "presigned-url-fence.labels" . | nindent 4 }}
  {{ with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
