apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssjdispatcher-deployment
spec:
  selector:
      {{- with .Values.selectorLabels }}
      matchLabels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  revisionHistoryLimit: 2
  strategy:
    {{- toYaml .Values.strategy | nindent 8 }}  
  template:
    metadata:
      {{- with .Values.labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.selectorLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      #serviceAccountName: "ssjdispatcher-service-account"
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken}}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      containers:
        - name: ssjdispatcher
          image: "quay.io/cdis/ssjdispatcher:2022.08"
          imagePullPolicy: Always
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          env:
            {{- with .Values.awsRegion  }}
            - name: AWS_REGION
              value: {{ . }}
            {{- end }}
            {{- with .Values.awsStsRegionalEndpoints  }}
            - name: AWS_STS_REGIONAL_ENDPOINTS
              value: {{ . }}
            {{- end }}
            {{- with .Values.gen3Namespace  }}
            - name: GEN3_NAMESPACE
              value: {{ . }}
            {{- end }}
            {{- with .Values.dispatcherJobNum  }}
            - name: JOB_NUM_MAX
              value: {{ . }}
            {{- end }}
         #   {{- with .Values.ssjdispatcherJobImages  }}
         #   - name: JOB_IMAGES
         #     value: {{ . }}
         #   {{- end }}

          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /_status
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /_status
              port: 8000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
