apiVersion: v1
kind: Service
metadata:
  name: revproxy-service
  labels:
    {{- include "revproxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.port }}
  ports:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  selector:
    {{- include "revproxy.selectorLabels" . | nindent 4 }}
