global:
  postgres:
    host: postgres-postgresql.postgres.svc.cluster.local
    master:
      username: postgres
      port: 5432
      # If password is left empty the lookup function will look for postgres master password
      password: 

postgres:
  # An array of databases to create.
  databases:
  - service: wts
    databaseName: wts
    username: wts
    password: wts_password
  - service: indexd
    databaseName: indexd
    username: indexd
    password: indexd_password